using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("ADOFAI Editor QoL")]
[assembly: AssemblyDescription("Native level-editor quality-of-life tools for A Dance of Fire and Ice")]
[assembly: AssemblyCompany("kiner5674")]
[assembly: AssemblyProduct("ADOFAI Editor QoL")]
[assembly: ComVisible(false)]
[assembly: Guid("B40FA5A7-1AD0-41FA-9504-FDE9D9EA6D76")]
// Version attributes are generated by build.ps1 from ModVersion.Current.
