// Generated by build.ps1. Do not edit by hand.
using System.Reflection;
[assembly: AssemblyVersion("0.17.3.0")]
[assembly: AssemblyFileVersion("0.17.3.0")]
[assembly: AssemblyInformationalVersion("0.17.3")]
